// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SkdaWazJ-ByA7EQ2tZmcc7ZuA-VZgOM',
    appId: '1:957534567289:android:2bec5cbd4f8c2f6e60cda8',
    messagingSenderId: '957534567289',
    projectId: 'snatchkart-ae263',
    storageBucket: 'snatchkart-ae263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCortMRR4VUkggSmDyRkhfiBLcRa9oPzg',
    appId: '1:957534567289:ios:3f783e5a4ea7597660cda8',
    messagingSenderId: '957534567289',
    projectId: 'snatchkart-ae263',
    storageBucket: 'snatchkart-ae263.appspot.com',
    androidClientId: '957534567289-e0nr2rb7e7e9si2ada7espk5i2v0hit0.apps.googleusercontent.com',
    iosClientId: '957534567289-gvel8t0hmmpaul24mi5bkb355uoht7h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.esnatch',
  );

}